#!/usr/bin/env bash

PATH=${HOME}/opt/ccollab-cmdline:${HOME}/opt/ocp/bin:/usr/local/sbin:${HOME}/opt/pulse-dev/bin:${HOME}/dotfiles/bin:${HOME}/opt/select-makepp:${PATH}:/opt/pulse-dev/bin

export PATH
